version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: nestorm187
      MYSQL_DATABASE: lightbox
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"

  app:
    build: .
    restart: always
    env_file:
      - .env
    environment:
      - DB_HOST=db
      - REDIS_HOST=redis
      - NODE_ENV=production
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db
      - redis
    command: npx nodemon --ignore uploads/ server.js
  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

volumes:
  db_data:
